/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.35
 * Generated at: 2026-05-29 06:50:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.entity.Company;

public final class company_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.entity.Company");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Company Management</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .container { margin-top: 30px; }\r\n");
      out.write("    .card { transition: transform 0.3s ease-in-out; }\r\n");
      out.write("    .card:hover { transform: translateY(-5px); }\r\n");
      out.write("    .btn { margin-top: 5px; }\r\n");
      out.write("    table th, table td { font-size: 0.9rem; }\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    /* FIXED ALIGNMENT */\r\n");
      out.write("    table th:nth-child(3),\r\n");
      out.write("    table th:nth-child(4),\r\n");
      out.write("    table td:nth-child(3),\r\n");
      out.write("    table td:nth-child(4) {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .material-icons {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        line-height: 1;\r\n");
      out.write("    }\r\n");
      out.write("    table {\r\n");
      out.write("    table-layout: fixed;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Allow wrapping everywhere */\r\n");
      out.write("td, th {\r\n");
      out.write("    word-break: break-word;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-wrapper {\r\n");
      out.write("    max-height: 400px;   /* adjust as needed */\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Control column widths */\r\n");
      out.write("th:nth-child(1), td:nth-child(1) { width: 30%; } /* Name */\r\n");
      out.write("th:nth-child(2), td:nth-child(2) { width: 30%; } /* Username */\r\n");
      out.write("th:nth-child(3), td:nth-child(3) { width: 20%; text-align:center; }\r\n");
      out.write("th:nth-child(4), td:nth-child(4) { width: 20%; text-align:center; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

List<Company> companies = (List<Company>) request.getAttribute("companies");
Company company = (Company) request.getAttribute("company");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<!-- BACK BUTTON -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col s12\">\r\n");
      out.write("            <a href=\"main\"\r\n");
      out.write("               class=\"btn grey darken-2 waves-effect waves-light\">\r\n");
      out.write("                ←\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- CREATE / UPDATE FORM -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col s12\">\r\n");
      out.write("        <div class=\"card hoverable\">\r\n");
      out.write("            <div class=\"card-content\">\r\n");
      out.write("                <span class=\"card-title\">\r\n");
      out.write("                    ");
      out.print( (company != null) ? "Edit Company" : "Create Company" );
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"companies\" method=\"post\" id=\"companyForm\">\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (company != null) { 
      out.write("\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( company.getId() );
      out.write("\">\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("                        <input id=\"name\" name=\"name\" type=\"text\" required\r\n");
      out.write("                               value=\"");
      out.print( company != null ? company.getName() : "" );
      out.write("\">\r\n");
      out.write("                        <label class=\"active\">Name</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("                        <input id=\"username\" name=\"username\" type=\"text\" required\r\n");
      out.write("                               value=\"");
      out.print( company != null ? company.getUsername() : "" );
      out.write("\">\r\n");
      out.write("                        <label class=\"active\">Username</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"input-field\">\r\n");
      out.write("                        <input id=\"password\" name=\"password\" type=\"password\" required>\r\n");
      out.write("                        <label class=\"active\">Password</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn green waves-effect waves-light\">\r\n");
      out.write("                        Save\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a href=\"companies\" class=\"btn grey waves-effect waves-light\">\r\n");
      out.write("                        Clear\r\n");
      out.write("                    </a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- TABLE -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col s12\">\r\n");
      out.write("        <div class=\"card hoverable\">\r\n");
      out.write("            <div class=\"card-content\">\r\n");
      out.write("                <span class=\"card-title\">Existing Companies</span>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"table-wrapper\">\r\n");
      out.write("               <table class=\"highlight\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Name</th>\r\n");
      out.write("                        <th>Username</th>\r\n");
      out.write("                        <th>Active</th>\r\n");
      out.write("                        <th>Actions</th> <!-- FIXED -->\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (companies != null) {
                           for (Company i : companies) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print( i.getName() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( i.getUsername() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                            <!-- ACTIVE ICON -->\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <a href=\"companies?toggle=");
      out.print( i.getId() );
      out.write("\"\r\n");
      out.write("                                   title=\"");
      out.print( i.isActive() ? "Deactivate" : "Activate" );
      out.write("\"\r\n");
      out.write("                                   style=\"display:inline-flex; align-items:center; justify-content:center;\">\r\n");
      out.write("                                    ");
 if (i.isActive()) { 
      out.write("\r\n");
      out.write("                                        <i class=\"material-icons green-text\">check</i>\r\n");
      out.write("                                    ");
 } else { 
      out.write("\r\n");
      out.write("                                        <i class=\"material-icons red-text\">close</i>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </td>\r\n");
      out.write("\r\n");
      out.write("                            <!-- EDIT BUTTON -->\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <a href=\"companies?edit=");
      out.print( i.getId() );
      out.write("\"\r\n");
      out.write("                                   class=\"btn-small blue waves-effect\"> <i class=\"material-icons\">edit</i></a>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    ");
   }
                       } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    M.AutoInit();\r\n");
      out.write("\r\n");
      out.write("    async function hash(string) {\r\n");
      out.write("        const utf8 = new TextEncoder().encode(string);\r\n");
      out.write("        const hashBuffer = await crypto.subtle.digest('SHA-256', utf8);\r\n");
      out.write("        const hashArray = Array.from(new Uint8Array(hashBuffer));\r\n");
      out.write("        return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"companyForm\")\r\n");
      out.write("	    .addEventListener(\"submit\", async function(e) {\r\n");
      out.write("	\r\n");
      out.write("		    e.preventDefault(); // IMPORTANT\r\n");
      out.write("		\r\n");
      out.write("		    const passwordInput = document.getElementById(\"password\");\r\n");
      out.write("		\r\n");
      out.write("		    const password = passwordInput.value;\r\n");
      out.write("		\r\n");
      out.write("		    const passwordHash = await hash(password);\r\n");
      out.write("		\r\n");
      out.write("		    passwordInput.value = passwordHash;\r\n");
      out.write("		\r\n");
      out.write("		    // submit AFTER hashing finishes\r\n");
      out.write("		    this.submit();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
