/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.35
 * Generated at: 2026-05-29 06:51:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.http.*;
import java.net.URI;
import com.fasterxml.jackson.databind.*;
import java.util.*;
import model.entity.InternshipApplication;
import model.entity.User;

public final class applications_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.net.http");
    _jspx_imports_packages.add("com.fasterxml.jackson.databind");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.net.URI");
    _jspx_imports_classes.add("model.entity.User");
    _jspx_imports_classes.add("model.entity.InternshipApplication");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Application Details</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Materialize CSS -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    .container {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("        transition: transform 0.3s ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th, td {\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 6px;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .badge {\r\n");
      out.write("        min-width: auto !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* MOBILE CARD TABLE */\r\n");
      out.write("    @media only screen and (max-width: 600px) {\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 95%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.4rem !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table,\r\n");
      out.write("        thead,\r\n");
      out.write("        tbody,\r\n");
      out.write("        th,\r\n");
      out.write("        td,\r\n");
      out.write("        tr {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 1px solid #e0e0e0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            border: none;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding: 8px 8px 8px 45%;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            min-height: 40px;\r\n");
      out.write("            word-break: break-word;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td:before {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("            top: 8px;\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td:nth-of-type(1):before { content: \"ID\"; }\r\n");
      out.write("        td:nth-of-type(2):before { content: \"Status\"; }\r\n");
      out.write("        td:nth-of-type(3):before { content: \"Student\"; }\r\n");
      out.write("        td:nth-of-type(4):before { content: \"Description\"; }\r\n");
      out.write("        td:nth-of-type(5):before { content: \"Actions\"; }\r\n");
      out.write("\r\n");
      out.write("        .action-buttons {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-small {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .new.badge {\r\n");
      out.write("            float: none !important;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

	User user = (User) request.getSession().getAttribute("user");
    String apiUrl = "http://localhost:8080/api/company/" +user.getId()+"/applications";

    List<InternshipApplication> applications = new ArrayList<>();

    try {
        HttpClient client = HttpClient.newHttpClient();

        HttpRequest httpRequest = HttpRequest.newBuilder()
                .uri(URI.create(apiUrl))
                .GET()
                .build();

        HttpResponse<String> httpResponse =
                client.send(httpRequest, HttpResponse.BodyHandlers.ofString());

        ObjectMapper mapper = new ObjectMapper();

        applications = Arrays.asList(
            mapper.readValue(httpResponse.body(), InternshipApplication[].class)
        );

    } catch (Exception e) {
        out.println("Error: " + e.getMessage());
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- BACK BUTTON -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col s12\">\r\n");
      out.write("            <a href=\"main\"\r\n");
      out.write("               class=\"btn grey darken-2 waves-effect waves-light\">\r\n");
      out.write("                ←\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- CARD -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col s12\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card hoverable\">\r\n");
      out.write("                <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"card-title\">\r\n");
      out.write("                        Internship Applications\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("                        <table class=\"highlight\">\r\n");
      out.write("\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>#</th>\r\n");
      out.write("                                    <th>Status</th>\r\n");
      out.write("                                    <th>Student</th>\r\n");
      out.write("                                    <th>Description</th>\r\n");
      out.write("                                    <th>Action</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("\r\n");
      out.write("                            <tbody>\r\n");
      out.write("\r\n");
      out.write("                            ");

                            int counter = 1;

                            for (InternshipApplication app : applications) {

                                    String status = app.getStatus();
                                    String colorClass = "";

                                    if ("ACCEPTED".equalsIgnoreCase(status)) {
                                        colorClass = "green";
                                    } else if ("REJECTED".equalsIgnoreCase(status)) {
                                        colorClass = "red";
                                    } else if ("PENDING".equalsIgnoreCase(status)) {
                                        colorClass = "orange";
                                    }
                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("\r\n");
      out.write("                                   <td>\r\n");
      out.write("									    ");
      out.print( counter++ );
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"new badge ");
      out.print( colorClass );
      out.write("\"\r\n");
      out.write("                                              data-badge-caption=\"\">\r\n");
      out.write("                                            ");
      out.print( status );
      out.write("\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        ");
      out.print( app.getStudentName() );
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        ");
      out.print( app.getInternshipDescription() );
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <div class=\"action-buttons\">\r\n");
      out.write("\r\n");
      out.write("                                            <button\r\n");
      out.write("                                                class=\"btn-small blue waves-effect\"\r\n");
      out.write("                                                onclick=\"reviewApplication('");
      out.print( app.getId() );
      out.write("')\">\r\n");
      out.write("                                                Edit\r\n");
      out.write("                                            </button>\r\n");
      out.write("\r\n");
      out.write("                                            ");

                                                if ("ACCEPTED".equalsIgnoreCase(status)) {
                                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                <button\r\n");
      out.write("                                                    class=\"btn-small green waves-effect\"\r\n");
      out.write("                                                    data-student-internship-id=\"");
      out.print( app.getStudentInternshipId() );
      out.write("\"\r\n");
      out.write("                                                    onclick=\"reviewStudentInternship(this)\">\r\n");
      out.write("                                                    Review\r\n");
      out.write("                                                </button>\r\n");
      out.write("\r\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                            ");

                                }
                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Materialize JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function reviewApplication(id) {\r\n");
      out.write("        window.location.href = \"reviewApplication.jsp?id=\" + id;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function reviewStudentInternship(btn) {\r\n");
      out.write("        const studentInternshipId = btn.dataset.studentInternshipId;\r\n");
      out.write("\r\n");
      out.write("        window.location.href =\r\n");
      out.write("            \"reviewStudentInternship.jsp?studentInternshipId=\" +\r\n");
      out.write("            encodeURIComponent(studentInternshipId);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
