/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.35
 * Generated at: 2026-05-29 06:50:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.entity.Internship;

public final class internship_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.entity.Internship");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Internship Management</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .container { margin-top: 30px; }\r\n");
      out.write("        .card { transition: transform 0.3s ease-in-out; }\r\n");
      out.write("        .card:hover { transform: translateY(-5px); }\r\n");
      out.write("        .btn { margin-top: 5px; }\r\n");
      out.write("        table th, table td { font-size: 0.9rem; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");

String error = (String) request.getAttribute("errorMessage");
if (error != null) {

      out.write("\r\n");
      out.write("    alert(\"");
      out.print( error );
      out.write("\");\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    // Data from servlet
    List<Internship> internships = (List<Internship>) request.getAttribute("internships");
    Internship internship = (Internship) request.getAttribute("internship"); // for edit

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("	    <div class=\"col s12\">\r\n");
      out.write("	        <a href=\"main\" \r\n");
      out.write("	           class=\"btn grey darken-2 waves-effect waves-light\">\r\n");
      out.write("	            ←\r\n");
      out.write("	        </a>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("    <!-- CREATE / UPDATE FORM -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col s12\">\r\n");
      out.write("            <div class=\"card hoverable\">\r\n");
      out.write("                <div class=\"card-content\">\r\n");
      out.write("                    <span class=\"card-title\">\r\n");
      out.write("                        ");
      out.print( (internship != null) ? "Edit Internship" : "Create Internship" );
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("					<form action=\"internships\" method=\"post\">\r\n");
      out.write("				    ");
 if(internship != null){ 
      out.write("\r\n");
      out.write("				        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( internship.getId() );
      out.write("\">\r\n");
      out.write("				        <input type=\"hidden\" name=\"_method\" value=\"put\">\r\n");
      out.write("				    ");
 } 
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <input id=\"description\" name=\"description\" type=\"text\" required\r\n");
      out.write("                                   value=\"");
      out.print( internship != null ? internship.getDescription() : "" );
      out.write("\">\r\n");
      out.write("                            <label class=\"active\">Description</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <input id=\"technologies\" name=\"technologies\" type=\"text\" required\r\n");
      out.write("                                   value=\"");
      out.print( internship != null ? internship.getTechnologies() : "" );
      out.write("\">\r\n");
      out.write("                            <label class=\"active\">Technologies</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"input-field col s12 m6\">\r\n");
      out.write("                                <input type=\"date\" name=\"startDate\"\r\n");
      out.write("                                       value=\"");
      out.print( internship != null ? internship.getStartDate() : "" );
      out.write("\">\r\n");
      out.write("                                <label class=\"active\">Start Date</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s12 m6\">\r\n");
      out.write("                                <input type=\"date\" name=\"endDate\"\r\n");
      out.write("                                       value=\"");
      out.print( internship != null ? internship.getEndDate() : "" );
      out.write("\">\r\n");
      out.write("                                <label class=\"active\">End Date</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <textarea name=\"requirements\" class=\"materialize-textarea\">");
      out.print( internship != null ? internship.getRequirements() : "" );
      out.write("</textarea>\r\n");
      out.write("                            <label class=\"active\">Additional Requirements</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <textarea name=\"constraints\" class=\"materialize-textarea\">");
      out.print( internship != null ? internship.getConstraints() : "" );
      out.write("</textarea>\r\n");
      out.write("                            <label class=\"active\">Constraints</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\" class=\"btn green waves-effect waves-light\">\r\n");
      out.write("                            Save\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a href=\"internships\" class=\"btn grey waves-effect waves-light\">\r\n");
      out.write("                            Clear\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- READ / DELETE CARDS -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col s12\">\r\n");
      out.write("        <div class=\"card hoverable\">\r\n");
      out.write("            <div class=\"card-content\">\r\n");
      out.write("                <span class=\"card-title\">Existing Internships</span>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (internships != null) {
                           for (Internship i : internships) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col s12 m6 l4\">\r\n");
      out.write("                            <div class=\"card blue-grey lighten-5 hoverable small\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <span class=\"card-title\" style=\"font-size:1.2rem;\">\r\n");
      out.write("                                        ");
      out.print( i.getDescription() );
      out.write("\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Technologies:</strong><br>\r\n");
      out.write("                                        ");
      out.print( i.getTechnologies() );
      out.write("\r\n");
      out.write("                                    </p>\r\n");
      out.write("\r\n");
      out.write("                                    <br>\r\n");
      out.write("\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Period:</strong><br>\r\n");
      out.write("                                        ");
      out.print( i.getStartDate() );
      out.write(' ');
      out.write('–');
      out.write(' ');
      out.print( i.getEndDate() );
      out.write("\r\n");
      out.write("                                    </p>\r\n");
      out.write("\r\n");
      out.write("                                    ");
 if(i.getRequirements() != null &&
                                          !i.getRequirements().isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <br>\r\n");
      out.write("\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <strong>Requirements:</strong><br>\r\n");
      out.write("                                            ");
      out.print( i.getRequirements() );
      out.write("\r\n");
      out.write("                                        </p>\r\n");
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    ");
 if(i.getConstraints() != null &&
                                          !i.getConstraints().isEmpty()) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        <br>\r\n");
      out.write("\r\n");
      out.write("                                        <p>\r\n");
      out.write("                                            <strong>Constraints:</strong><br>\r\n");
      out.write("                                            ");
      out.print( i.getConstraints() );
      out.write("\r\n");
      out.write("                                        </p>\r\n");
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card-action\">\r\n");
      out.write("                                    <a href=\"internships?edit=");
      out.print( i.getId() );
      out.write("\"\r\n");
      out.write("                                       class=\"btn-small blue waves-effect waves-light\">\r\n");
      out.write("                                        Edit\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"internships?delete=");
      out.print( i.getId() );
      out.write("\"\r\n");
      out.write("                                       class=\"btn-small red waves-effect waves-light\"\r\n");
      out.write("                                       onclick=\"return confirm('Delete this internship?')\">\r\n");
      out.write("                                        Delete\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
   }
                       } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    M.AutoInit();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
