/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.35
 * Generated at: 2026-05-29 06:46:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col s12 m8 offset-m2 l6 offset-l3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <span class=\"card-title center-align\">Login</span>\r\n");
      out.write("                        <form id=\"loginForm\" action=\"login\" method=\"post\">\r\n");
      out.write("                            <div class=\"input-field\">\r\n");
      out.write("                                <input id=\"username\" name=\"username\" type=\"text\" required>\r\n");
      out.write("                                <label for=\"username\">Username</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field\">\r\n");
      out.write("                                <input id=\"password\" name=\"password\" type=\"password\" required>\r\n");
      out.write("                                <label for=\"password\">Password</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"center-align\">\r\n");
      out.write("                                <button class=\"btn waves-effect waves-light\" type=\"submit\">Login</button>\r\n");
      out.write("                            </div>           \r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 String error = request.getParameter("error"); 
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("		  async function hash(string) {\r\n");
      out.write("		  const utf8 = new TextEncoder().encode(string);\r\n");
      out.write("		  const hashBuffer = await crypto.subtle.digest('SHA-256', utf8);\r\n");
      out.write("		  const hashArray = Array.from(new Uint8Array(hashBuffer));\r\n");
      out.write("		  const hashHex = hashArray\r\n");
      out.write("		    .map((bytes) => bytes.toString(16).padStart(2, '0'))\r\n");
      out.write("		    .join('');\r\n");
      out.write("		  return hashHex;\r\n");
      out.write("		}\r\n");
      out.write("		  \r\n");
      out.write("		  const error = \"");
      out.print( error );
      out.write("\";\r\n");
      out.write("			 if (error === \"invalid_credentials\") {\r\n");
      out.write("			   alert(\"Wrong credentials! Try again.\");\r\n");
      out.write("			 } \r\n");
      out.write("		\r\n");
      out.write("		document.getElementById(\"loginForm\").addEventListener(\"submit\", async function(event) {\r\n");
      out.write("		  event.preventDefault(); // stop form submission temporarily\r\n");
      out.write("		  const passwordInput = document.getElementById(\"password\").value;\r\n");
      out.write("		  const hashPass = await hash(passwordInput); // wait for the hash\r\n");
      out.write("		  console.log(hashPass);\r\n");
      out.write("		\r\n");
      out.write("		 \r\n");
      out.write("		  document.getElementById(\"password\").value = hashPass;\r\n");
      out.write("		\r\n");
      out.write("		  this.submit(); // now submit the form\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
